[package]
name = "geforcedrvchk3"
version = "0.3.1"
authors = ["Matti J. Karki <mjk@iki.fi>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curl = "0.4.25"
json = "0.12.0"
regex = "1.3.3"